In [1]:
import os
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [2]:
path_fault1_ex = 'C:/Users/baek/Desktop/NURO/data/fault1/external'
path_fault1_in = 'C:/Users/baek/Desktop/NURO/data/fault1/internal'

path_normal_ex = 'C:/Users/baek/Desktop/NURO/data/normal/external'
path_normal_in = 'C:/Users/baek/Desktop/NURO/data/normal/internal'

In [3]:
dat_f1 = [[] for i in range(0,2)]
dat_f2 = [[] for i in range(0,2)]
dat_n = []

In [4]:
temp =pd.read_csv(path_fault1_ex + '/'+ os.listdir(path_fault1_ex)[0], sep = '\t' )
dat_f1[0].append(temp)
temp =pd.read_csv(path_fault1_ex + '/'+os.listdir(path_fault1_ex)[1], sep = '\t' )
dat_f1[0].append(temp)
temp =pd.read_csv(path_fault1_ex + '/'+os.listdir(path_fault1_ex)[2], sep = '\t' )
dat_f1[0].append(temp)
temp =pd.read_csv(path_fault1_ex + '/'+os.listdir(path_fault1_ex)[3], sep = '\t' )
dat_f1[0].append(temp)


temp =pd.read_csv(path_fault1_in + '/'+os.listdir(path_fault1_in)[0], sep = ',' , low_memory=False)
dat_f1[1].append(temp)
temp =pd.read_csv(path_fault1_in + '/'+os.listdir(path_fault1_in)[1], sep = ',' , low_memory=False)
dat_f1[1].append(temp)
temp =pd.read_csv(path_fault1_in + '/'+os.listdir(path_fault1_in)[2], sep = ',' , low_memory=False)
dat_f1[1].append(temp)
temp =pd.read_csv(path_fault1_in + '/'+os.listdir(path_fault1_in)[3], sep = ',' , low_memory=False)
dat_f1[1].append(temp)

temp =pd.read_csv(path_normal_ex + '/'+os.listdir(path_normal_ex)[0], sep = '\t' )
dat_n.append(temp)
temp =pd.read_csv(path_normal_ex + '/'+os.listdir(path_normal_ex)[1], sep = '\t' )
dat_n.append(temp)
temp =pd.read_csv(path_normal_ex + '/'+os.listdir(path_normal_ex)[2], sep = '\t' )
dat_n.append(temp)
temp =pd.read_csv(path_normal_ex + '/'+os.listdir(path_normal_ex)[3], sep = '\t' )
dat_n.append(temp)

In [49]:
v1_n = dat_f1[1][0].loc[dat_f1[1][0]['CoreSN'] == 'core0'+str(1),:].reset_index().drop(labels = 'index', axis=1)
v1_m = dat_f1[1][0].loc[dat_f1[1][0]['CoreSN'] == 'core0'+str(2),:].reset_index().drop(labels = 'index', axis=1)

v15_n = dat_f1[1][1].loc[dat_f1[1][1]['CoreSN'] == 'core0'+str(1),:].reset_index().drop(labels = 'index', axis=1)
v15_m = dat_f1[1][1].loc[dat_f1[1][1]['CoreSN'] == 'core0'+str(2),:].reset_index().drop(labels = 'index', axis=1)

v2_n = dat_f1[1][2].loc[dat_f1[1][2]['CoreSN'] == 'core0'+str(1),:].reset_index().drop(labels = 'index', axis=1)
v2_m = dat_f1[1][2].loc[dat_f1[1][2]['CoreSN'] == 'core0'+str(2),:].reset_index().drop(labels = 'index', axis=1)

v25_n = dat_f1[1][3].loc[dat_f1[1][3]['CoreSN'] == 'core0'+str(1),:].reset_index().drop(labels = 'index', axis=1)
v25_m = dat_f1[1][3].loc[dat_f1[1][3]['CoreSN'] == 'core0'+str(2),:].reset_index().drop(labels = 'index', axis=1)

In [92]:
v1_n.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,46901.000000,46901.000000,46901.000000,46901.000000,46901.000000
mean,1468.855254,0.578824,1.182827,0.057053,41.462121
std,236.731345,101.759971,143.696543,8.014508,0.691688
min,1115.953248,-122.154916,-297.228741,-15.472932,39.370133
25%,1253.169115,-113.887976,-111.956812,-7.701140,40.927767
50%,1466.235352,0.000000,1.209516,0.000000,41.706533
75%,1682.020542,114.214302,113.478905,7.842445,42.001967
max,1835.932907,123.351446,297.228741,14.483794,42.592800

In [93]:
v1_m.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,46901.000000,46901.000000,46901.000000,46901.000000,46901.000000
mean,3954.544109,0.568272,-1.232972,-0.027452,43.687061
std,236.726678,101.766912,171.458814,10.223313,1.126250
min,3601.664157,-123.242671,-297.379320,-17.521859,39.638700
25%,3738.822263,-114.105527,-149.176790,-10.315288,43.076200
50%,3951.807245,0.000000,0.000000,0.000000,44.069800
75%,4167.899726,114.105527,147.112945,10.103330,44.526367
max,4321.652409,124.221651,297.228741,18.369691,45.036633

In [94]:
v15_n.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,48183.000000,48183.000000,48183.000000,48183.000000,48183.000000
mean,2193.858793,-0.184862,-0.106590,0.031664,43.635824
std,235.947952,153.098214,154.760174,8.148345,1.496120
min,1835.272857,-181.220026,-297.228741,-15.331626,39.209000
25%,1979.363337,-170.777576,-115.109852,-7.771792,42.646467
50%,2194.637500,0.000000,3.427305,0.000000,43.828133
75%,2406.849957,170.886351,118.816361,8.195708,44.526367
max,2555.232284,181.437577,297.228741,14.201184,46.379400

In [95]:
v15_m.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,48183.000000,48183.000000,48183.000000,48183.000000,48183.000000
mean,4679.668732,-0.105674,-1.868965,-0.090136,44.997622
std,235.868999,153.169837,175.728211,10.205113,1.151336
min,4321.056210,-186.441252,-297.228741,-17.168595,40.283200
25%,4465.264059,-171.212678,-149.705929,-10.315288,44.392133
50%,4680.588584,0.000000,0.000000,0.000000,44.929233
75%,4892.395146,171.212678,148.434347,10.244635,45.896000
max,5041.029452,186.006149,297.228741,17.592511,47.077633

In [97]:
v2_n.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,52094.000000,52094.000000,52094.000000,52094.000000,52094.000000
mean,2579.769374,-0.160616,0.719715,0.012731,45.128372
std,237.042798,203.355842,170.159013,9.412721,3.978620
min,2225.192654,-252.359220,-316.705397,-19.924049,29.084467
25%,2363.705369,-228.102278,-133.510807,-8.831582,44.123533
50%,2578.880464,0.000000,0.000000,0.000000,46.621100
75%,2793.842115,228.102278,140.449613,9.184845,47.749000
max,2945.174270,249.204730,297.228741,21.125144,48.500967

In [98]:
v2_m.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,52094.000000,52094.000000,52094.000000,52094.000000,52094.000000
mean,5065.307419,-0.193302,-0.333495,-0.035920,44.727764
std,236.834199,203.210307,188.449881,11.117667,3.740371
min,4710.711356,-251.815343,-297.228741,-22.326239,29.084467
25%,4849.504168,-228.102278,-159.452231,-10.597898,43.586400
50%,5064.210821,0.000000,0.000000,0.000000,46.030267
75%,5279.182343,228.102278,163.089735,10.739204,47.399933
max,5435.952813,251.053914,297.228741,22.184934,47.883267

In [99]:
v25_n.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,69629.000000,69629.000000,69629.000000,69629.000000,69629.000000
mean,2585.502109,-0.268281,0.954292,0.038399,44.672856
std,235.911111,255.093985,189.892692,9.711192,2.686182
min,2229.072785,-314.252495,-2426.131833,-20.418618,36.281733
25%,2371.448201,-284.883103,-145.368769,-9.255498,42.646467
50%,2585.207882,0.000000,0.000000,0.000000,45.009767
75%,2798.076800,284.556776,153.232595,9.255498,46.728500
max,2949.123692,326.435353,2322.896848,21.337102,48.688933

In [100]:
v25_m.describe()

,encoderAngle,encoderVelocity,CommandTorque,ActualTorque,BoardTemp
count,69629.000000,69629.000000,69629.000000,69629.000000,69629.000000
mean,5071.271153,-0.277731,-0.541701,-0.049633,45.043553
std,235.809039,255.011027,200.436810,11.316040,2.349517
min,4714.832752,-316.863107,-301.938908,-22.114281,36.711433
25%,4857.372092,-284.665552,-173.062461,-11.092467,43.774400
50%,5070.701022,0.000000,0.000000,0.000000,46.030300
75%,5283.586148,284.774327,172.262058,10.880509,46.782233
max,5438.101347,313.382290,813.382093,22.326239,48.178700